config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/users/auth/sign_up' => 'omniauth_callbacks#sign_up'
  end

  resources :users

  resources :requests, shallow: true do
    resources :comments, only: [:create]
    resources :answers, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :requests, shallow: true do
        resources :answers, only: [:create]
        resources :comments, only: [:create]
      end
    end
  end

  mount ActionCable.server => '/cable'

  root to: "requests#index"
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :comments
  has_many :answers
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_request, only: %i(show edit update destroy)
  after_action :publish_request, only: [:create]
  # after_action :delete_publish_request, only: [:destroy]

  authorize_resource
  respond_to :html, :json

  def index
    @requests = Request.all
  end

  def show
    @comments = @request.comments
    @answers = @request.answers
  end

  def new
    @request = Request.new
  end

  def edit; end

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    if @request.save
      redirect_to @request
    else
      render :new
    end
  end

  def update
    if @request.update(request_params)
      redirect_to @request
    else
      render :edit
    end
  end

  def destroy
    @request.destroy if current_user.owner?(@request)
    redirect_to root_path
  end

  private

  def load_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:title, :body, :user_id)
  end

  def publish_request
    return if @request.errors.any?
    ActionCable.server.broadcast(
        'requests',
        ApplicationController.render(
            partial: 'requests/list',
            locals: { request: @request }
        )
    )
  end

  # TODO: create AC for destroy Request
  # def delete_publish_request
  #   return if @request.errors.any?
  #   ActionCable.server.broadcast(
  #       'requests',
  #       ApplicationController.render(
  #           partial: 'requests/list',
  #           locals: { request: @request.id }
  #       )
  #   )
  # end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_list.html.slim
.collection-item id=dom_id(request)
  = link_to request.title, request

app/views/requests/_request.html.slim
.row
  .col.s8
    .request-title
      h4
        =request.title
.row
  .col.s8
    .request-body
      =request.body

- if can?(:update, @request)
  .row
    .col.s2
      = link_to 'Редактировать', request_path(request), class: 'btn waves-light', remote: true, 'data-toggle' => 'modal', 'data-target' => 'edit_form', id: 'edit_button'
    .col.s2
      = link_to 'Удалить', request_path(request), method: :delete, data: {confirm: 'вы действительно хотите удалить заявку ?'}, class: 'btn red-light'

.row
  .col.s8
    = render 'comments/list', request: request, comment: request.comments.build

.row
  .col.s8
    = render 'answers/list', request: request

#edit_form.modal
  = form_for request, remote: true do |f|
    .row
      .col.s12
        h5 изменить заявку
        = f.text_field :title
        = f.text_area :body, class: 'materialize-textarea'
        = f.submit 'Сохранить', class: 'btn waves-light'

app/views/requests/index.html.slim
h3 Все заявки
.requests-list.collection
  - if @requests.present?
    - @requests.each do |request|
      = render 'requests/list', request: request
  - else
    div
      .col.s6.offset-s3.center
        p Заявок нет

.action-btn style="bottom: 45px; right: 24px;"
  = link_to 'Создать заявку', new_request_path, class: 'btn waves-effect waves-light'

app/views/requests/new.html.slim
= render 'common/errors', resource: @request
= form_for @request do |f|
  .row
    .input-field.col.s8
      = f.text_field :title, placeholder: 'Название заявки'
    .input-field.col.s8
      = f.text_area :body, placeholder: 'Текст заявки', class: 'materialize-textarea'
    br

  = f.button class: 'btn waves-effect waves-light'
    | Создать заявку
    i.material-icons.right
      | send

app/views/requests/show.html.slim
#request data-id="#{@request.id}"
  = render @request

app/views/requests/update.js.erb
$('.request-errors').html('')
<% if @request.errors.present? %>
  <% @request.errors.full_messages.each do |message| %>
    $('.request-errors').append('<%= j message %>')
  <% end %>
<% else %>
  $('.request').html('<%= j render @request %>')
<% end %>